name: Workflow Sync

on:
  push:
    branches:
      - master
env:
  DRY_RUN: false
  REPOSITORIES: |
    vcmi-mods/vcmi-extras@vcmi-1.7
    vcmi-mods/horn-of-the-abyss@vcmi-1.7
    vcmi-mods/tides-of-war@vcmi-1.7
    vcmi-mods/wake-of-gods@vcmi-1.7
    vcmi-mods/HD-remastered@vcmi-1.7
    vcmi-mods/small-era-mods@vcmi-1.7
    vcmi-mods/czech-translation@vcmi-1.7
    vcmi-mods/vietnamese-translation@vcmi-1.7
    vcmi-mods/tears-of-ashan@vcmi-1.7
    vcmi-mods/alternate-townscreens@vcmi-1.7
    vcmi-mods/lotrd-townscreens@vcmi-1.7
    vcmi-mods/the-lost-tales@vcmi-1.7
    vcmi-mods/h3landscape@vcmi-1.7
    vcmi-mods/new-interface-mod@vcmi-1.7
    vcmi-mods/reinforcements-spell@vcmi-1.7
    vcmi-mods/an-expansion@vcmi-1.7
    vcmi-mods/tartarus-town@vcmi-1.7
    vcmi-mods/new-pavilion@vcmi-1.7
    vcmi-mods/ruins-town@vcmi-1.7
    vcmi-mods/newtown-terrains@vcmi-1.7
    vcmi-mods/forge@vcmi-1.7
    vcmi-mods/forge2k@vcmi-1.7
    vcmi-mods/asphalt-terrain@vcmi-1.7
    vcmi-mods/hirki-plus-patch@vcmi-1.7
    vcmi-mods/market-of-time@vcmi-1.7
    vcmi-mods/new-old-spells-plus@vcmi-1.7
    vcmi-mods/ab-bad-ending-assets@vcmi-1.7
    vcmi-mods/new-monsters-pack@vcmi-1.7
    vcmi-mods/haven-town@vcmi-1.7
    vcmi-mods/refugee-town@vcmi-1.7
    vcmi-mods/preserve-town@vcmi-1.7
    vcmi-mods/vcmi-extras@vcmi-1.8
    vcmi-mods/horn-of-the-abyss@vcmi-1.8
    vcmi-mods/new-pavilion@vcmi-1.8
    vcmi-mods/newtown-terrains@vcmi-1.8
    vcmi-mods/sylvan-town@vcmi-1.8
  
  WORKFLOW_FILES: |
    .github=./

jobs:
  Github_Workflow_Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master

      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          COMMIT_MESSAGE: "Automated synchronization of Github workflows"
